name: CI

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: [1.13.6]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Fetch tools
        run: go get -v golang.org/x/lint/golint

      - name: Test and lint
        run: |
          go test ./...
          go list ./... | xargs -n1 golint -set_exit_status

      - name: Build
        run: go build -v .
