on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: [1.13.6]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-stretch
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Fetch tools
        run: go get -v golang.org/x/lint/golint

      - name: Test and lint
        run: |
          go test ./...
          go list ./... | xargs -n1 golint -set_exit_status

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -v -o hello-darwin64
          GOOS=linux GOARCH=amd64 go build -v -o hello-linux64
          GOOS=windows GOARCH=amd64 go build -v -o hello-windows64

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Hello ${{ github.ref }}

      - name: Upload artifact (darwin)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello-darwin64
          asset_name: hello-darwin64
          asset_content_type: application/octet-stream

      - name: Upload artifact (linux)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello-linux64
          asset_name: hello-linux64
          asset_content_type: application/octet-stream

      - name: Upload artifact (windows)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello-windows64
          asset_name: hello-windows64
          asset_content_type: application/octet-stream
